spring:
  # 运行环境 dev:开发环境|test:测试环境|prod:生产环境
  profiles:
    active: #spring.profiles.active#

  #添加对jsp支持
  mvc:
    view:
      prefix:  /WEB-INF/views/
      suffix: .jsp
      #静态文件地址
    static-path-pattern: /**

server:
  #  Tomcat  服务配置server:server:server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 80
  servlet:
    context-path: /

mybatis:
  #实体类所做包
  type-aliases-package: com.yoyi.pay.dao
  #mapper.xml所在位置
  mapperLocations: classpath:mapper/*.xml
  #MyBatis相关自定义配置
  configLocation: classpath:mybatis-config.xml